version: '3.7'
services:
  redis:
    image: redis:6.0-rc1-alpine
    networks:
      - redis-net
    ports:
      - "6379:6379"
    container_name: redis
#    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: always
#зайти в контейнер docker exec -it redis redis-cli

#зайти в контейнер docker exec -it postgresql psql -U root -d users
networks:
  redis-net:
  postgres-net:

volumes:
  redis-data:
  postgres-data:






