version: '3.7'
services:
  ClientProfileLoader:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: profile_loader_db
      PGDATA: var/lib/postgresql/data

    volumes:

      - db:/var/lib/postgresql/data
      - ./DUMP/project:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local
