version: '3.2'
services:
  ClientProfileLoader:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: profile_loader_db
      PGDATA: var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test_topic:1:3"
    depends_on:
      - zookeeper

    volumes:

      - db:/var/lib/postgresql/data
      - ./DUMP/project:/docker-entrypoint-initdb.d

volumes:
  db:
    driver: local

